### ISSUE TITLE
QuantityImpl::one does not have a unit

### ISSUE THREAD

**Issue by JoelGaechter** [datahaki/tensor#15]
When calling `Scalar::one` on a `Quantity` the resulting value does not have a unit.
Its implementation seems to lack `ofUnit`, see `QuantityImpl::zero` for comparison.

**Comment by datahaki** [comment]
`Scalar::one` gives **multiplicative 1** so that always
    scalar.multiply(scalar.one()) == scalar

So far there was no need anywhere for a function that maps
    345[km] to 1[km]

anyways, i think you can implement a workaround using `QuantityUnit`, `QuantityMagnitude`.

**Comment by JoelGaechter** [comment]
okay, then I misunderstood what the function is supposed to do

**Comment by datahaki** [comment]
Thanks to your input, I am now wondering why QuantityImpl::arg gives a value with unit!?

Unfortunately, my mathematica installation is inactive and I can't cross-check at the moment.
