### ISSUE TITLE
DateTimeScalar getLocalDateTime Method

### ISSUE THREAD

**Issue by omkirch** [datahaki/tensor#28]
I would like to have a get Method for the private attribute `LocalDateTime` in `DateTimeScalar`.
This seems useful for applications.

**Comment by datahaki** [comment]
Thank you for pointing that out! The method was missing indeed.
`DateTimeScalar` now has a method to extract the `LocalDateTime`.

However, I have moved `DateTimeScalar` to the test scope, from where users can copy the code and customize.
This is until it is reintroduced again in the near future.
